Allow ha vault deployments
hybrid-cloud-patterns/common pull request #132
Opened 2022-08-26 14:16 UTC by ruromero

Signed-off-by: ruromero <rromerom@redhat.com>

Detect if vault deployments has more pods and assume `vault-0` as the leader.
Make the other `vault-x` join the raft cluster as followers and finally unseal the followers.

Additionally: Added check for missing serviceAccount token secret

2022-08-27 13:55 UTC, mbaldessari requested changes
Apologies for CI not running right away (I hope I fixed it). Could you fix the warnings from the linters?:
```
Error: fqcn-builtins Use FQCN for builtin actions.
Error: fqcn-builtins Use FQCN for builtin actions.
Error: yaml no new line character at the end of file
Warning: var-spacing Jinja2 variables and filters should have spaces before and after.
```
Also can you try and use something other than json_query() . That function belongs to community.general and when we ran the unsealing tasks from within the cluster (by settings `insecureUnsealVaultInsideCluster: true`) we run it using the `registry.redhat.io/ansible-automation-platform-22/ee-supported-rhel8:latest` container and that one does not have it. (I know this is a bit annoying, but it was either using that container or rolling our own and maintaining it :) )

2022-08-29 08:51 UTC, ruromero commented
@mbaldessari sure it was easier to avoid using it than I expected, it should be fine now

2022-08-29 09:01 UTC, mbaldessari commented
Awesome, thanks a lot @ruromero! I'll do a smoke test today or tomorrow and then merge it

2022-08-29 10:55 UTC, mbaldessari approved these changes

2022-08-29 11:00 UTC, mbaldessari commented
I tested this in non-HA and it worked okay, so I'll merge it now. I might silence that "Get Pods" loop a bit as it is a bit verbose, but that's for later ;) Thanks again!

2022-08-29 11:00 UTC, merged