DNM/WIP stop fetching values files over URL. Use local files from git
hybrid-cloud-patterns/common pull request #98
Opened 2022-06-30 12:54 UTC by mbaldessari

Starting with ArgoCD 2.3 (openshift-gitops 1.4.x) [1] we do can use values
files from git directly. This avoids us fetching values files over http
and potentially avoid issue https://issues.redhat.com/browse/GITOPS-2069
"argocd application do not update when values file changed in helm repo"

Note this is not working just yet. At least vault fails because even
though it has "VALUES FILES: /values-global.yaml, /values-hub.yaml"
it is looking them up relative to the vault chart:

    helm template . --name-template vault --namespace vault --kube-version 1.23
    --set server.route.host= --set server.route.tls.termination=edge
    --set server.image.repository=registry.connect.redhat.com/hashicorp/vault
    --set server.image.tag=1.10.3-ubi --set global.pattern=multicloud-gitops
    --set injector.enabled=false --set ui.enabled=true --set
    global.targetRevision=v0.20.1 --set global.namespace=vault --set
    global.hubClusterDomain=apps.bandini-dc.blueprints.rhecoeng.com --set
    global.localClusterDomain=apps.bandini-dc.blueprints.rhecoeng.com --set
    server.route.enabled=true --set
    global.repoURL=https://helm.releases.hashicorp.com --set
    global.valuesDirectoryURL= --set global.openshift=true --set
    ui.serviceType=LoadBalancer --values
    /tmp/e1dc8cf5-dc7a-4675-a940-cfc811a2d712/vault/values-global.yaml
    --values /tmp/e1dc8cf5-dc7a-4675-a940-cfc811a2d712/vault/values-hub.yaml
    ...
    Error: open /tmp/8a879537-5f64-40c0-a56e-2e80d77488b0/vault/values-global.yaml: no such file or directory

[1] https://github.com/argoproj/argo-cd/blob/bb77664b6f0299bb332843bcd2524820c7ba1558/reposerver/repository/repository.go#L674

2022-07-01 07:20 UTC, mbaldessari commented
So now it works. And I correctly get MCG deployed and working. What I am not sure about is the following: Will there be any external charts in the future (it's not the case now with vault) that they will need the correct values files to function properly?
I.e. Should we still fetch values files over http when we are in the presence of an external chart?

2022-07-06 12:18 UTC, beekhof requested changes

2022-07-06 12:18 UTC, beekhof commented on acm/templates/policies/application-policies.yaml
> +                      - "{{ default "" .valuesDirectoryURL }}/values-{{ .name }}.yaml"
Pretty sure this is not needed/wrong

2022-07-07 06:57 UTC, beekhof commented on clustergroup/templates/applications.yaml
> +      {{- end }}
```suggestion
      {{- else }}
      - "/values-global.yaml"
      - "/values-{{ $.Values.clusterGroup.name }}.yaml"
      {{- end }}
```

2022-07-07 07:00 UTC, beekhof commented on acm/templates/policies/application-policies.yaml
> +                      - "{{ default "" .valuesDirectoryURL }}/values-{{ .name }}.yaml"
```suggestion
                      - "/values-global.yaml"
                      - "/values-{{ .name }}.yaml"
```

2022-07-08 07:55 UTC, mbaldessari commented
Dropped in favour of #113

2022-07-08 07:55 UTC, closed without merging